<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="rPagos.aspx.cs" Inherits="pAnalisisMD.Registros.rPagos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    
    <div class="card">
           <div class="panel" style="background-color: #0094ff">
        <div class="panel-heading" style="font-family: Arial Black; font-size: 20px; text-align:center; color: Black">Registro de pagos</div>
    </div>
        <div class="panel-body">
            <div class="card-body">
                <div class="container">

                    <div class="form-group-row">

                        <%--PagoId--%>
                        <div class="col-md-2 col-md-offset-3">
                            <asp:Label ID="PagoIdLabel" Text="PagoId" runat="server" />
                            <asp:TextBox ID="PagoIdTextBox" class="form-control input-sm" TextMode="Number" runat="server" placeholder="0"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ValidationGroup="Buscar" ControlToValidate="PagoIdTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                        </div>

                        <%--Buscar Button--%>
                        <div class="col-md-2 col-sm-2 col-xs-2">
                            <div class="input-group-append">
                                <br />
                                <asp:Button Text="Buscar" class="btn btn-primary" runat="server" ID="BuscarButton" />
                            </div>
                        </div>

                        <%--Fecha--%>
                        <div class="col-md-2 col-sm-1 col-xs-3">
                            <asp:Label Text="Fecha" runat="server" />
                            <asp:TextBox ID="FechaTextBox" class="form-control input-sm" TextMode="Date" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RFVFFecha" ValidationGroup="Guardar" ControlToValidate="FechaTextBox" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                            <br />
                            <br />
                        </div>

                        <%--AnalisisId--%>
                        <div class="col-md-2 col-md-offset-3">
                            <asp:Label ID="AnalisisIdLabel" Text="AnalisisId" runat="server" />
                            <asp:DropDownList ID="AnalisisDropdownList" class="form-control input-sm" TextMode="Number" runat="server" placeholder="0"></asp:DropDownList>
                            <asp:RequiredFieldValidator ID="RFVId" ValidationGroup="Buscar" ControlToValidate="AnalisisDropdownList" runat="server" ErrorMessage="*" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                        </div>

                        
                             <%--Balance--%>
                        <div class="col-md-3 col-md-offset-2">
                            <asp:Label ID="Balance" runat="server" Text="Balance">Balance</asp:Label><br />
                            <asp:TextBox ID="BalanceTextBox" ReadOnly="true" runat="server" class="form-control input-sm"></asp:TextBox>
                        </div>


                        <!--Monto-->
                        <div class="col-md-2 col-md-offset-5">
                            <br />
                            <asp:Label ID="Monto" runat="server" Text="Monto">Monto a pagar:</asp:Label><br />
                            <asp:TextBox ID="MontoTextBox" class="form-control input-sm" TextMode="Number" MaxLength="9" runat="server" placeholder="0"></asp:TextBox>
                        </div>
                    </div>


                    <%--Agregar Button--%>
                    <div class="col-md-2 col-sm-2 col-xs-2">
                        <div class="input-group-append">
                            <br />
                            <br />
                            <asp:Button Text="Agregar" class="btn btn-primary" runat="server" ID="AgregarButton" OnClick="AgregarButton_Click" />
                        </div>
                        <br />
                        <br />
                    </div>
                </div>
                </div>

              <asp:GridView ID="DetalleGridView" class="col-md-3 col-md-offset-3" runat="server" DataKeyNames="DetalleId" AllowPaging="true" PageSize="10" ShowHeaderWhenEmpty="false" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333"  GridLines="None" Width="767px" AutoGenerateColumns="false"   >
                    <Columns>
                        <asp:BoundField DataField="PagoId" HeaderText="PagoId" />
                        <asp:BoundField />
                        <asp:BoundField DataField="MontoPago" HeaderText="MontoPago" />
                        <asp:BoundField />
                    </Columns>

                    <EmptyDataTemplate>
                        <div style="text-align: center">Se han eliminado todas las filas</div>
                    </EmptyDataTemplate>
                    <AlternatingRowStyle BackColor="White" />

                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />

                </asp:GridView>
                <div class="panel">
                    <div class="text-center">
                        <div class="form-group">
                            <asp:Button ID="NuevoButton" runat="server" Text="Nuevo" class="btn btn-primary" />
                            <asp:Button ID="GuardarButton" runat="server" Text="Guardar" class="btn btn-success" ValidationGroup="Guardar" />
                            <asp:Button ID="EliminarButton" runat="server" Text="Eliminar" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
 
        </div>
    </div>
</asp:Content>